export const courses = [
    {
        id: 1,
        title: "Introduction to Web Development",
        instructor: "John Doe",
        category: "programming",
        duration: "8 weeks",
        price: 99.99,
        image: "assets/images/webDev.png",
        featured: true,
    },
    {
        id: 2,
        title: "Advanced JavaScript",
        instructor: "Jane Smith",
        category: "programming",
        duration: "6 weeks",
        price: 129.99,
        image: "assets/images/advJs.png",
        featured: true,
    },
    {
        id: 3,
        title: "UI/UX Design Fundamentals",
        instructor: "Alice Johnson",
        category: "design",
        duration: "4 weeks",
        price: 79.99,
        image: "assets/images/UIUXDesignFundamentals.png",
        featured: false,
    },
    {
        id: 4,
        title: "Digital Marketing Strategies",
        instructor: "Bob Wilson",
        category: "business",
        duration: "5 weeks",
        price: 89.99,
        image: "assets/images/DigitalMarketingStrategies.png",
        featured: false,
    },
    {
        id: 5,
        title: "Data Science with Python",
        instructor: "Emily Brown",
        category: "programming",
        duration: "10 weeks",
        price: 149.99,
        image: "assets/images/DataSciencewithPython.png",
        featured: true,
    },
];
export const instructors = [
    {
        id: 1,
        name: "John Doe",
        expertise: "Web Development",
        image: "assets/images/ins1.avif",
    },
    {
        id: 2,
        name: "Jane Smith",
        expertise: "JavaScript",
        image: "assets/images/ins2.avif",
    },
    {
        id: 3,
        name: "Alice Johnson",
        expertise: "UI/UX Design",
        image: "assets/images/ins4.avif",
    },
    {
        id: 4,
        name: "Bob Wilson",
        expertise: "Digital Marketing",
        image: "assets/images/ins5.avif",
    },
    {
        id: 5,
        name: "Emily Brown",
        expertise: "Data Science",
        image: "assets/images/ins3.avif",
    },
    {
        id: 6,
        name: "Emily Brown",
        expertise: "Data Science",
        image: "assets/images/ins6.avif",
    },
    {
        id: 7,
        name: "Emily Brown",
        expertise: "Data Science",
        image: "assets/images/ins1.avif",
    },
    {
        id: 8,
        name: "Emily Brown",
        expertise: "Data Science",
        image: "assets/images/ins3.avif",
    },
];
